language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.3
    - android-23

    # Additional components
    - extra-android-m2repository
    - extra-android-support

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle

addons:
  apt_packages:
    - pandoc
  artifacts:
    paths:
      - $(git ls-files -o | grep build/outputs | tr "\n" ":")

before_install:
  - pip install --user codecov
  - chmod +x gradlew

before_script:
  - echo no | android create avd --force -n test -t 3 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - ./gradlew check -PdisablePreDex --continue --stacktrace
  - ./gradlew build jacocoTestReport assembleAndroidTest -PdisablePreDex --continue --stacktrace
  - ./gradlew connectedAndroidTest -PdisablePreDex --continue --stacktrace

after_success:
  - bash <(curl -s https://codecov.io/bash)