language: android
jdk: oraclejdk8

env:
  global:
    # wait up to 10 minutes for adb to connect to emulator
    - ADB_INSTALL_TIMEOUT=10

android:
  components:
    - tools
    - build-tools-25.0.1
    - android-25
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository

    # Emulator for the tests
    - sys-img-android-25-armeabi-v7a

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle

addons:
  apt_packages:
    - pandoc
  artifacts:
    paths:
      - $(git ls-files -o | grep build/outputs | tr "\n" ":")

before_install:
  - pip install --user codecov
  - chmod +x gradlew

script:
  - ./gradlew check -PdisablePreDex --continue --stacktrace
  - ./gradlew build jacocoTestReport assembleAndroidTest -PdisablePreDex --continue --stacktrace
  - ./gradlew connectedAndroidTest -PdisablePreDex --continue --stacktrace

after_success:
  - bash <(curl -s https://codecov.io/bash)